demo_upload_and_download_file/config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'resumes/downloadFile/:id', to:'resumes#downloadFile', as: 'download_file'
end

demo_upload_and_download_file/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demo_upload_and_download_file/app/models/resume.rb
class Resume < ApplicationRecord
end

demo_upload_and_download_file/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

demo_upload_and_download_file/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create

    @resume = Resume.new(resume_params)
    file_upload = params[:resume][:title]
    File.open(Rails.root.join('public','files', file_upload.original_filename), "wb") do |file| 
       file.write(file_upload.read)
    end
    @resume.title = file_upload.original_filename
    
    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def downloadFile
    resume = set_resume
    send_file Rails.root.join('public', 'files', resume.title)
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:title)
    end
end

demo_upload_and_download_file/app/helpers/application_helper.rb
module ApplicationHelper
end

demo_upload_and_download_file/app/helpers/resumes_helper.rb
module ResumesHelper
end

demo_upload_and_download_file/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoUploadAndDownloadFile</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

demo_upload_and_download_file/app/views/resumes/_form.html.erb
<%= form_with(model: resume, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.file_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

demo_upload_and_download_file/app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

demo_upload_and_download_file/app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.title %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Download', {controller: "resumes", action: "downloadFile", id: resume} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

demo_upload_and_download_file/app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

demo_upload_and_download_file/app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resume.title %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>